In [2]:
from model import *
from evaldavis2017 import *
from utils import *
from dataset.dataset import DAVIS_MO_Test

Testloader = DAVIS_MO_Test('../data.nosync/DAVIS2017', resolution='480p', imset='20{}/{}.txt'.format(17,'val'), single_object=(17==16))


Reading file ../data.nosync/DAVIS2017/ImageSets/2017/val.txt


In [37]:
for e in Testloader:
    print(e)


(tensor([2]), {'name': 'bike-packing', 'num_frames': 69, 'size_480p': (480, 910)})
(tensor([1]), {'name': 'blackswan', 'num_frames': 50, 'size_480p': (480, 854)})
(tensor([2]), {'name': 'bmx-trees', 'num_frames': 80, 'size_480p': (480, 854)})
(tensor([1]), {'name': 'breakdance', 'num_frames': 84, 'size_480p': (480, 854)})
(tensor([1]), {'name': 'camel', 'num_frames': 90, 'size_480p': (480, 854)})
(tensor([1]), {'name': 'car-roundabout', 'num_frames': 75, 'size_480p': (480, 854)})
(tensor([1]), {'name': 'car-shadow', 'num_frames': 40, 'size_480p': (480, 854)})
(tensor([1]), {'name': 'cows', 'num_frames': 104, 'size_480p': (480, 854)})
(tensor([1]), {'name': 'dance-twirl', 'num_frames': 90, 'size_480p': (480, 854)})
(tensor([1]), {'name': 'dog', 'num_frames': 60, 'size_480p': (480, 854)})
(tensor([3]), {'name': 'dogs-jump', 'num_frames': 66, 'size_480p': (480, 854)})
(tensor([1]), {'name': 'drift-chicane', 'num_frames': 52, 'size_480p': (480, 854)})
(tensor([1]), {'name': 'drift-straight

In [38]:
for V in list(Testloader)[:1]:
    print(V)

(tensor([2]), {'name': 'bike-packing', 'num_frames': 69, 'size_480p': (480, 910)})


In [22]:
! pip install imgaug

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 948.0/948.0 kB 993.0 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 1.4 MB/s eta 0:00:0000:0100:01


In [23]:
import pandas as pd 
import numpy as np

In [45]:
g_measures = ['Vide0','J&F-Mean', 'J-Mean', 'J-Recall', 'J-Decay', 'F-Mean', 'F-Recall', 'F-Decay']
g_res = np.array(['bike',0.82510419,0.79958112,1.,0.0564815,0.85062727,1.,0.08967042])

In [46]:
df = pd.DataFrame(columns=g_measures)
df.loc[0] = g_res

In [47]:
df

Vide0    J&F-Mean      J-Mean J-Recall    J-Decay      F-Mean F-Recall  \
0  bike  0.82510419  0.79958112      1.0  0.0564815  0.85062727      1.0   

      F-Decay  
0  0.08967042

In [44]:
np.array(['aaa',0.82510419,0.79958112,1.,0.0564815,0.85062727,1.,0.08967042])

array(['aaa', '0.82510419', '0.79958112', '1.0', '0.0564815',
       '0.85062727', '1.0', '0.08967042'], dtype='<U32')

In [42]:
df.loc[len(df)] = g_res

In [1]:
from dataset.coco import Coco_MO_Train
COCO_ROOT = '../data.nosync/Ms-COCO/'
Trainset1 = Coco_MO_Train('{}train2017'.format(COCO_ROOT),'{}annotations/instances_train2017.json'.format(COCO_ROOT))

In [4]:
from torch.utils import data
Trainloader1 = data.DataLoader(Trainset1, batch_size=1, num_workers=1,shuffle = True, pin_memory=True)

In [5]:
loader_iter1 = iter(Trainloader1)